baseURL = 'https://kyon213.github.io/AlephFrags/'
locale = 'en-us'
title = 'Aleph Frags'
theme = 'hugo-book'

[params]
  BookSection = 'docs'
  BookSearchConfig = true
  BookCollapseSection = true
  BookSubtitle = "I saw the teeming sea; I saw daybreak and nightfall; I saw the multitudes of America; I saw a silvery cobweb in the center of a black pyramid."
[menu]
  [[menu.after]]
    name = "GitHub"
    url = "https://github.com/kyon213/AlephFrags"
    weight = 10
